name: xo_game
description: A Flutter app to play Tic Tac Toe with Glassmorphic UI

publish_to: 'none'

version: 1.0.2+2

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.6.0
  flutter_svg: ^2.0.10+1
  glassmorphism: ^3.0.0
  lottie: ^3.1.3
  provider: ^6.0.5
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/xo_logo.svg
    - assets/animations/bg-anim.json

  fonts:
    - family: LuckiestGuy
      fonts:
        - asset: assets/fonts/LuckiestGuy-Regular.ttf
